# ------------------------------------
# Matias Finochio - 2026 - MIT License
# Generated by tools/gendoc.nim — run `nimble docs` to regenerate.
# ------------------------------------

{.error: "gim.doc.nim is documentation only — do not compile".}


# ── backend.nim ─────────────────────────────────────────

## Data struct with window title, width and height.
## Passed into `init` as the window config.
BackendConfig* = object

## Internal state of the backend.
## It holds the SDL window pointer, the opengl context, a flag
## for the running state and a timestamp for delta time.
## It is used as a global named `gBackend` because there is only
## one window.
Backend* = object

## Reads the state of the `running` flag (from the Backend object)
## This is called every frame inside the game loop.
## The game keeps running while this returns true and stops when
## it returns false.
proc isRunning*(): bool {.inline.}

## Loads the OpenGL extensions so function pointers can be resolved.
## --
## **NOTE**: This also sets the alpha blend mode once to
## `GL_BLEND`, which is the "normal" transparency mode.
## This might change in the future, it would be nice to have
## configurable blend modes instead of setting one as default.
proc initGl*() {.raises: [].}

## Sets a color and clears the color buffer.
## This is called at the start of `onDraw`.
## --
## **NOTE**: depth buffer is not being used at the moment.
## This might change in the future for things like
## Z-layer ordering.
proc clearScreen*(r, g, b, a: float32) {.raises: [].}

## This is the main function from the backend.
## It does a few things lised below:
## - initializes SDL (video & joystick, although the latter is unused)
## - sets OPENGL version hints (3.3 core)
## - requests an OPENGL double buffer.
## - creates the window
## - creates the OPENGL context and attaches it to the window.
## - calls the `initGl` and `renderer.initRenderer` functions.
## - sets the `running` flag to true.
## - when the program fails for any reason it sets `running` to false.
##
## **NOTE**: This might change in the future.
## Currently the program failing just means "stop running". At some
## point I would want to have better logging and error handling.
proc init*(cfg: BackendConfig)

## This does the opposite to the `init` function.
## It tears everything down in the reverse order
## ** OPENGL context -> window -> SDL quit. **
## It sets the `running` flag to false.
## SDL and OPENGL use C pointers, so we have to clean
## them up manually.
proc shutdown*()

## This maps SDL events into the library's own input system.
## It starts by calling `inputBeginFrame` which returns a
## snapshot of the previous frame.
## Then matches each SDL event into the specific library
## event.
##
## **NOTE**: This is missing a LOT of events such as
## window resize, scroll wheel, gamepad later on.
proc pollEvents*()

## This computes the time since the last call (in seconds)
## It uses SDL's tick counter for this.
## This is called once per frame inside the game loop.
proc deltaTime*(): float32

## This flips the back buffer to the screen.
## Is is called at the end of every frame.
proc swapBuffers*()


# ── color.nim ───────────────────────────────────────────

Color* = object

func rgba*(r, g, b, a: float32): Color {.inline.}

func rgb*(r, g, b: float32): Color {.inline.}

func rgba8*(r, g, b, a: uint8): Color {.inline.}

func rgb8*(r, g, b: uint8): Color {.inline.}

func hex*(v: uint32): Color {.inline.}

func `==`*(a, b: Color): bool {.inline.}

func lerp*(a, b: Color, t: float32): Color {.inline.}

func withAlpha*(c: Color, a: float32): Color {.inline.}

White* = Color(r: 1f, g: 1f, b: 1f, a: 1f)

Black* = Color(r: 0f, g: 0f, b: 0f, a: 1f)

Transparent* = Color(r: 0f, g: 0f, b: 0f, a: 0f)

Red* = Color(r: 1f, g: 0f, b: 0f, a: 1f)

Green* = Color(r: 0f, g: 1f, b: 0f, a: 1f)

Blue* = Color(r: 0f, g: 0f, b: 1f, a: 1f)


# ── gamemacro.nim ───────────────────────────────────────

macro game*(title: static string, width, height: static int, body: untyped): untyped


# ── input.nim ───────────────────────────────────────────

Key* = enum

MouseButton* = enum

proc inputBeginFrame*()

proc inputHandleKey*(sc: Scancode, down: bool)

proc inputHandleMouseButton*(btn: uint8, down: bool)

proc inputHandleMouseMove*(x, y: int32)

proc isKeyDown*(k: Key): bool {.inline.}

proc isKeyPressed*(k: Key): bool {.inline.}

proc isKeyReleased*(k: Key): bool {.inline.}

proc isMouseDown*(btn: MouseButton): bool {.inline.}

proc isMousePressed*(btn: MouseButton): bool {.inline.}

proc isMouseReleased*(btn: MouseButton): bool {.inline.}

proc mousePos*(): tuple[x, y: int32] {.inline.}


# ── rect2.nim ───────────────────────────────────────────

Rect2*[T: Scalar] = object

func rect2*[T: Scalar](x, y, w, h: T): Rect2[T] {.inline.}

func rect2*[T: Scalar](pos, size: Vec2[T]): Rect2[T] {.inline.}

func left*[T: Scalar](r: Rect2[T]): T {.inline.}

func top*[T: Scalar](r: Rect2[T]): T {.inline.}

func right*[T: Scalar](r: Rect2[T]): T {.inline.}

func bottom*[T: Scalar](r: Rect2[T]): T {.inline.}

func center*[T: Scalar](r: Rect2[T]): Vec2[T] {.inline.}

func contains*[T: Scalar](r: Rect2[T], p: Vec2[T]): bool {.inline.}

func overlaps*[T: Scalar](a, b: Rect2[T]): bool {.inline.}

func `==`*[T: Scalar](a, b: Rect2[T]): bool {.inline.}

Rect2px* = Rect2[Pixels]

Rect2w* = Rect2[WorldUnits]


# ── renderer.nim ────────────────────────────────────────

Shader* = object

proc newShader*(vertSrc, fragSrc: string): Shader

proc use*(s: Shader) {.inline.}

proc setUniform*(s: Shader, name: cstring, x, y: float32)

proc setUniform*(s: Shader, name: cstring, r, g, b, a: float32)

proc setUniformMat4*(s: Shader, name: cstring, m: var array[16, float32])

Mesh* = object

proc newQuadMesh*(): Mesh

proc draw*(m: Mesh) {.inline.}

proc initRenderer*(width, height: int)

proc drawRect*(pos: Vec2px, size: Vec2px, color: Color)

proc drawTexture*(pos: Vec2px, tex: var Texture)


# ── scene.nim ───────────────────────────────────────────

SceneImpl* = object

SceneStatus* = enum

SceneEvent* = enum

SceneTransition* = object

Scene* = object

SceneCmd* = object

func isActive*(s: Scene): bool {.inline.}

func isPaused*(s: Scene): bool {.inline.}

func isStopped*(s: Scene): bool {.inline.}

func isTransitioning*(s: Scene): bool {.inline.}


# ── texture.nim ─────────────────────────────────────────

Texture* = object

proc isValid*(t: var Texture): bool {.inline.}

proc bindGL*(t: var Texture) {.inline.}

proc loadTexture*(path: string): Texture


# ── transform2.nim ──────────────────────────────────────

Transform2* = object

func transform2*(pos: Vec2px, rotation = Radians(0f), scale = Vec2[WorldUnits](x: WorldUnits(1f), y: WorldUnits(1f))): Transform2 {.inline.}

func identity*(_: typedesc[Transform2]): Transform2 {.inline.}

func forward*(t: Transform2): Vec2[float32] {.inline.}

func rotated*(t: Transform2, delta: Radians): Transform2 {.inline.}

func translated*(t: Transform2, delta: Vec2px): Transform2 {.inline.}


# ── types.nim ───────────────────────────────────────────

Pixels* = distinct float32

WorldUnits* = distinct float32

Radians* = distinct float32

Degrees* = distinct float32

ZLayer* = distinct int32

EntityId* = distinct uint32

func `+`*(a, b: Pixels): Pixels {.inline.}

func `-`*(a, b: Pixels): Pixels {.inline.}

func `*`*(a: Pixels, b: float32): Pixels {.inline.}

func `/`*(a: Pixels, b: float32): Pixels {.inline.}

func `<`*(a, b: Pixels): bool {.inline.}

func `<=`*(a, b: Pixels): bool {.inline.}

func `==`*(a, b: Pixels): bool {.inline.}

func `+`*(a, b: WorldUnits): WorldUnits {.inline.}

func `-`*(a, b: WorldUnits): WorldUnits {.inline.}

func `*`*(a: WorldUnits, b: float32): WorldUnits {.inline.}

func `/`*(a: WorldUnits, b: float32): WorldUnits {.inline.}

func `<`*(a, b: WorldUnits): bool {.inline.}

func `<=`*(a, b: WorldUnits): bool {.inline.}

func `==`*(a, b: WorldUnits): bool {.inline.}

DegToRad* = PI.float32 / 180'f32

RadToDeg* = 180'f32 / PI.float32

func toRadians*(d: Degrees): Radians {.inline.}

func toDegrees*(r: Radians): Degrees {.inline.}

func `<`*(a, b: ZLayer): bool {.inline.}

func `<=`*(a, b: ZLayer): bool {.inline.}

func `==`*(a, b: ZLayer): bool {.inline.}

const InvalidEntity*: EntityId = EntityId(0)

func `==`*(a, b: EntityId): bool {.inline.}

func isValid*(id: EntityId): bool {.inline.}


# ── vec2.nim ────────────────────────────────────────────

Scalar* = concept s

Vec2*[T: Scalar] = object

func vec2*[T: Scalar](x, y: T): Vec2[T] {.inline.}

func vec2*[T: Scalar](v: float32): Vec2[T] {.inline.}

func `+`*[T: Scalar](a, b: Vec2[T]): Vec2[T] {.inline.}

func `-`*[T: Scalar](a, b: Vec2[T]): Vec2[T] {.inline.}

func `*`*[T: Scalar](a: Vec2[T], s: float32): Vec2[T] {.inline.}

func `/`*[T: Scalar](a: Vec2[T], s: float32): Vec2[T] {.inline.}

func `==`*[T: Scalar](a, b: Vec2[T]): bool {.inline.}

func dot*[T: Scalar](a, b: Vec2[T]): float32 {.inline.}

func lengthSq*[T: Scalar](a: Vec2[T]): float32 {.inline.}

func length*[T: Scalar](a: Vec2[T]): float32 {.inline.}

func normalize*[T: Scalar](a: Vec2[T]): Vec2[T] {.inline.}

func neg*[T: Scalar](a: Vec2[T]): Vec2[T] {.inline.}

Vec2px* = Vec2[Pixels]

Vec2w* = Vec2[WorldUnits]
