import std/[os, strutils, algorithm, sequtils]

const
  SrcDir     = "src"
  OutputFile = "gim.doc.nim"
  SkipFiles  = ["gim.nim"]

const DeclKeywords = ["proc ", "func ", "template ", "macro ", "iterator "]

type
  Decl = object
    docs:      seq[string]
    signature: string

  Section = object
    filename: string
    decls:    seq[Decl]

func indentOf(line: string): int =
  for c in line:
    if   c == ' ':  inc result
    elif c == '\t': result += 2
    else: break

func parenBalance(line: string): int =
  for c in line:
    case c
    of '(', '[': inc result
    of ')', ']': dec result
    else: discard

func normWhitespace(s: string): string =
  var prev = ' '
  for c in s:
    if c == ' ' and prev == ' ': continue
    result.add c
    prev = c
  result = result.strip()

func isExportedDecl(line: string): bool =
  let s = line.strip()
  if s.contains("`="):  return false
  for kw in DeclKeywords:
    if s.startsWith(kw) and '*' in s: return true

func isTypeBlockOpener(line: string): bool =
  line.strip() == "type"

func isExportedTypeEntry(line: string): bool =
  let s = line.strip()
  s.len > 0 and '*' in s and '=' in s and not s.startsWith('#')

func stripProcBody(raw: string): string =
  var depth      = 0
  var inBacktick = false
  var i          = 0
  while i < raw.len:
    if raw[i] == '`':
      inBacktick = not inBacktick
      inc i; continue
    if inBacktick:
      inc i; continue
    case raw[i]
    of '(', '[', '{': inc depth
    of ')', ']', '}': dec depth
    of '=':
      if depth == 0:
        let prev = if i > 0: raw[i - 1] else: ' '
        let next = if i + 1 < raw.len: raw[i + 1] else: ' '
        if prev notin {'!', '<', '>', '='} and next != '=':
          return raw[0 ..< i].strip()
    else: discard
    inc i
  raw.strip()

proc parseFile(path: string): Section =
  result.filename = path.extractFilename()

  let lines = readFile(path).splitLines()
  let n     = lines.len

  var i             = 0
  var pendingDocs   : seq[string]
  var inTypeBlock   = false
  var typeBlockBase = 0

  while i < n:
    let line     = lines[i]
    let stripped = line.strip()

    if stripped.len == 0:
      pendingDocs = @[]
      inc i
      continue

    if stripped.startsWith("##"):
      pendingDocs.add stripped
      inc i
      continue

    if stripped.startsWith('{') or
       stripped.startsWith('#') or
       stripped.startsWith("import") or
       stripped.startsWith("export"):
      inc i
      continue

    if isTypeBlockOpener(line):
      inTypeBlock   = true
      typeBlockBase = indentOf(line)
      pendingDocs   = @[]
      inc i
      continue

    if inTypeBlock and
       indentOf(line) > typeBlockBase and
       isExportedTypeEntry(line):

      result.decls.add Decl(docs: pendingDocs, signature: normWhitespace(stripped))
      pendingDocs = @[]

      let entryIndent = indentOf(line)
      inc i
      while i < n:
        let bl = lines[i]
        if bl.strip().len == 0: inc i; continue
        if indentOf(bl) > entryIndent: inc i
        else: break
      continue

    if isExportedDecl(line):
      inTypeBlock = false

      var sigLines = @[line]
      var balance  = parenBalance(line)
      var j        = i + 1
      while balance > 0 and j < n:
        sigLines.add lines[j]
        balance += parenBalance(lines[j])
        inc j

      let raw = sigLines.mapIt(it.strip()).join(" ")
      let sig = stripProcBody(normWhitespace(raw))

      result.decls.add Decl(docs: pendingDocs, signature: sig)
      pendingDocs = @[]

      let declIndent = indentOf(line)
      i = j
      while i < n:
        let bl = lines[i]
        if bl.strip().len == 0: inc i; continue
        if indentOf(bl) > declIndent: inc i
        else: break
      continue

    # anything else
    if indentOf(line) <= typeBlockBase: inTypeBlock = false
    if stripped.len > 0: pendingDocs = @[]
    inc i

proc write(sections: seq[Section]) =
  var buf = ""

  buf &= "# ------------------------------------\n"
  buf &= "# Matias Finochio - 2026 - MIT License\n"
  buf &= "# Generated by tools/gendoc.nim — run `nimble docs` to regenerate.\n"
  buf &= "# ------------------------------------\n"
  buf &= "\n"
  buf &= "{.error: \"gim.doc.nim is documentation only — do not compile\".}\n"

  for sec in sections:
    if sec.decls.len == 0: continue

    let pad = max(4, 52 - sec.filename.len)
    let bar = "─".repeat(pad)
    buf &= "\n\n# ── " & sec.filename & " " & bar & "\n"

    for decl in sec.decls:
      buf &= "\n"
      for doc in decl.docs:
        buf &= doc & "\n"
      buf &= decl.signature & "\n"

  writeFile(OutputFile, buf)
  echo "wrote ", OutputFile, " (", $buf.len, " bytes)"

var files: seq[string]
for f in walkFiles(SrcDir / "*.nim"):
  if f.extractFilename() notin SkipFiles:
    files.add f
files.sort()

write files.mapIt(parseFile(it))
